ALTER TABLE "Task" ALTER COLUMN status DROP DEFAULT;
ALTER TABLE "ExamAnalysisTask" ALTER COLUMN status DROP DEFAULT;
ALTER TABLE "Task" ALTER COLUMN status TYPE text;
ALTER TABLE "ExamAnalysisTask" ALTER COLUMN status TYPE text;
DROP TYPE IF EXISTS "TaskStatus";
