import { Task, Flashcard, Ticket, StudentProfile, InstituteAdvisor, InstituteStudent, Exam } from '@/lib/types';

// ===== Mock Tasks =====
export const MOCK_TASKS: Task[] = [
  {
    id: '1',
    studentId: 's1',
    subject: 'ریاضی',
    subjectColor: '#5E6AD2',
    topic: 'حد و پیوستگی',
    fieldType: 'کنکور',
    activityTypes: ['مطالعه', 'تست آموزشی'],
    targetTimeMinutes: 90,
    actualTimeMinutes: null,
    targetTestCount: 30,
    actualTestCount: null,
    completed: null,
    date: new Date().toISOString().split('T')[0],
    order: 1,
    createdBy: 'advisor',
  },
  {
    id: '2',
    studentId: 's1',
    subject: 'فیزیک',
    subjectColor: '#D89614',
    topic: 'الکتریسیته ساکن',
    fieldType: 'کنکور',
    activityTypes: ['مطالعه', 'تست سنجشی'],
    targetTimeMinutes: 60,
    actualTimeMinutes: null,
    targetTestCount: 20,
    actualTestCount: null,
    completed: null,
    date: new Date().toISOString().split('T')[0],
    order: 2,
    createdBy: 'advisor',
  },
  {
    id: '3',
    studentId: 's1',
    subject: 'شیمی',
    subjectColor: '#E5484D',
    topic: 'الکتروشیمی',
    fieldType: 'کنکور',
    activityTypes: ['مرور', 'تست آموزشی'],
    targetTimeMinutes: 45,
    actualTimeMinutes: null,
    targetTestCount: 15,
    actualTestCount: null,
    completed: null,
    date: new Date().toISOString().split('T')[0],
    order: 3,
    createdBy: 'advisor',
  },
  {
    id: '4',
    studentId: 's1',
    subject: 'زیست',
    subjectColor: '#9B8CF0',
    topic: 'ژنتیک',
    fieldType: 'کنکور',
    activityTypes: ['مطالعه'],
    targetTimeMinutes: 75,
    actualTimeMinutes: null,
    targetTestCount: 25,
    actualTestCount: null,
    completed: null,
    date: new Date().toISOString().split('T')[0],
    order: 4,
    createdBy: 'advisor',
  },
  {
    id: '5',
    studentId: 's1',
    subject: 'ادبیات',
    subjectColor: '#A8A0D8',
    topic: 'آرایه‌های ادبی',
    fieldType: 'نهایی',
    activityTypes: ['مرور', 'تست آموزشی'],
    targetTimeMinutes: 40,
    actualTimeMinutes: null,
    targetTestCount: 10,
    actualTestCount: null,
    completed: null,
    date: new Date().toISOString().split('T')[0],
    order: 5,
    createdBy: 'student',
  },
  {
    id: '6',
    studentId: 's1',
    subject: 'عربی',
    subjectColor: '#4A7FB5',
    topic: 'ترجمه و صرف',
    fieldType: 'نهایی',
    activityTypes: ['مطالعه', 'تست سنجشی'],
    targetTimeMinutes: 35,
    actualTimeMinutes: null,
    targetTestCount: 10,
    actualTestCount: null,
    completed: null,
    date: new Date().toISOString().split('T')[0],
    order: 6,
    createdBy: 'student',
  },
  // Tasks for other students (advisor-created)
  {
    id: '7',
    studentId: 's2',
    subject: 'ریاضی',
    subjectColor: '#5E6AD2',
    topic: 'مشتق',
    fieldType: 'کنکور',
    activityTypes: ['مطالعه', 'تست آموزشی'],
    targetTimeMinutes: 60,
    actualTimeMinutes: null,
    targetTestCount: 20,
    actualTestCount: null,
    completed: null,
    date: new Date().toISOString().split('T')[0],
    order: 1,
    createdBy: 'advisor',
  },
  {
    id: '8',
    studentId: 's2',
    subject: 'فیزیک',
    subjectColor: '#D89614',
    topic: 'مغناطیس',
    fieldType: 'کنکور',
    activityTypes: ['مطالعه'],
    targetTimeMinutes: 45,
    actualTimeMinutes: null,
    targetTestCount: 15,
    actualTestCount: null,
    completed: null,
    date: new Date().toISOString().split('T')[0],
    order: 2,
    createdBy: 'advisor',
  },
  {
    id: '9',
    studentId: 's4',
    subject: 'زیست',
    subjectColor: '#9B8CF0',
    topic: 'سلول',
    fieldType: 'کنکور',
    activityTypes: ['مرور', 'تست سنجشی'],
    targetTimeMinutes: 90,
    actualTimeMinutes: null,
    targetTestCount: 40,
    actualTestCount: null,
    completed: null,
    date: new Date().toISOString().split('T')[0],
    order: 1,
    createdBy: 'advisor',
  },
  {
    id: '10',
    studentId: 's5',
    subject: 'شیمی',
    subjectColor: '#E5484D',
    topic: 'تعادل شیمیایی',
    fieldType: 'کنکور',
    activityTypes: ['مطالعه', 'تست آموزشی'],
    targetTimeMinutes: 30,
    actualTimeMinutes: null,
    targetTestCount: 10,
    actualTestCount: null,
    completed: null,
    date: new Date().toISOString().split('T')[0],
    order: 1,
    createdBy: 'advisor',
  },
];

// ===== Mock Flashcards =====
export const MOCK_FLASHCARDS: Flashcard[] = [
  {
    id: '1',
    front: 'حد تابع f(x) وقتی x به سمت a میل می‌کند چیست؟',
    back: 'مقدار L است به طوری که برای هر ε>0 یک δ>0 وجود دارد...',
    isSystem: true,
    mastery: 'review',
    subject: 'ریاضی',
  },
  {
    id: '2',
    front: 'قانون اول ترمودینامیک چیست؟',
    back: 'ΔU = Q - W: تغییر انرژی درونی برابر با گرمای وارد شده منهای کار انجام شده',
    isSystem: true,
    mastery: 'mastered',
    subject: 'فیزیک',
  },
  {
    id: '3',
    front: 'DNA replication در کدام فاز سلولی اتفاق می‌افتد؟',
    back: 'فاز S (Synthesis) از اینترفاز',
    isSystem: true,
    mastery: 'weak',
    subject: 'زیست',
  },
  {
    id: '4',
    front: 'الکترونگاتیویتی چیست؟',
    back: 'تمایل اتم برای جذب الکترون‌ها در پیوند کووالانسی',
    isSystem: true,
    mastery: 'review',
    subject: 'شیمی',
  },
  {
    id: '5',
    front: 'فرق تشبیه و استعاره چیست؟',
    back: 'تشبیه: کلمه شبیه یا مانند ذکر می‌شود. استعاره: کلمه شبیه حذف می‌شود',
    isSystem: true,
    mastery: 'mastered',
    subject: 'ادبیات',
  },
  {
    id: '6',
    front: 'مشتق تابع f(x) = x³ چیست؟',
    back: 'f\'(x) = 3x²',
    isSystem: true,
    mastery: 'mastered',
    subject: 'ریاضی',
  },
  {
    id: '7',
    front: 'قانون دوم نیوتون چیست؟',
    back: 'F = ma: نیرو برابر جرم ضربدر شتاب',
    isSystem: true,
    mastery: 'review',
    subject: 'فیزیک',
  },
  {
    id: '8',
    front: 'فرق DNA و RNA چیست؟',
    back: 'DNA دو رشته‌ای با دئوکسی‌ریبوز، RNA تک رشته‌ای با ریبوز',
    isSystem: true,
    mastery: 'review',
    subject: 'زیست',
  },
  {
    id: '9',
    front: 'قانون بویل چیست؟',
    back: 'در دمای ثابت، حجم گاز با فشار نسبت عکس دارد: PV = const',
    isSystem: true,
    mastery: 'weak',
    subject: 'شیمی',
  },
  {
    id: '10',
    front: 'جملات واره و وابسته به ترتیب چیست؟',
    back: 'جمله واره: جمله مستقل. جمله وابسته: جمله که به تنهایی معنی کامل نمی‌دهد',
    isSystem: true,
    mastery: 'review',
    subject: 'عربی',
  },
  {
    id: '11',
    front: 'فرمول شتاب گرانشی چیست؟',
    back: 'g = GM/r² که G ثابت گرانش، M جرم سیاره و r شعاع',
    isSystem: true,
    mastery: 'mastered',
    subject: 'فیزیک',
  },
  {
    id: '12',
    front: 'مفهوم هیدروژن در پیوند شیمیایی چیست؟',
    back: 'پیوند هیدروژنی: جاذبه بین هیدروژن متصل به F,O,N با اتم الکترونگاتیو دیگر',
    isSystem: true,
    mastery: 'weak',
    subject: 'شیمی',
  },
];

// ===== Mock Tickets =====
export const MOCK_TICKETS: Ticket[] = [
  {
    id: '1',
    topic: 'مشکل فنی',
    subject: 'ثبت زمان مطالعه کار نمی‌کنه',
    message: 'وقتی زمان مطالعه رو ثبت می‌کنم ذخیره نمی‌شه',
    status: 'answered',
    createdAt: '2025-01-15',
  },
  {
    id: '2',
    topic: 'پیشنهاد',
    subject: 'افزودن ویجت آب و هوا',
    message: 'خوبه یه ویجت آب و هوا هم اضافه بشه',
    status: 'open',
    createdAt: '2025-01-20',
  },
];

// ===== Subjects =====
export const SUBJECTS = [
  { name: 'ریاضی', color: '#5E6AD2' },
  { name: 'فیزیک', color: '#6E7AE0' },
  { name: 'شیمی', color: '#3EBA8C' },
  { name: 'زیست', color: '#9B8CF0' },
  { name: 'ادبیات', color: '#D89614' },
  { name: 'عربی', color: '#8A8F98' },
  { name: 'دینی', color: '#5C6066' },
  { name: 'زبان', color: '#4A7FB5' },
  { name: 'تاریخ', color: '#7A8FA0' },
  { name: 'جغرافیا', color: '#6B7A8F' },
  { name: 'فلسفه', color: '#A8A0D8' },
  { name: 'اقتصاد', color: '#5A8A7A' },
];

// ===== Avatars =====
export const AVATARS = [
  '🦊', '🐺', '🦁', '🐯', '🦅', '🐉',
];

// ===== Topics per subject =====
export const TOPICS: Record<string, string[]> = {
  'ریاضی': ['حد و پیوستگی', 'مشتق', 'انتگرال', 'هندسه تحلیلی', 'احتمال', 'ماتریس', 'دنباله'],
  'فیزیک': ['الکتریسیته ساکن', 'الکتریسیته جاری', 'مغناطیس', 'نوسان و موج', 'نور', 'اتم'],
  'شیمی': ['الکتروشیمی', 'تعادل شیمیایی', 'سینتیک', 'ترمودینامیک', 'حلول', 'اسید و باز'],
  'زیست': ['ژنتیک', 'سلول', 'گیاه‌شناسی', 'ایمنی', 'عصب', 'تولید مثل'],
  'ادبیات': ['آرایه‌های ادبی', 'وزن و قافیه', 'تاریخ ادبیات', 'نقد ادبی', 'دستور زبان'],
  'عربی': ['ترجمه و صرف', 'نحو', 'بلاغه', 'متن خوانی'],
  'دینی': ['اخلاق', 'تاریخ اسلام', 'قرآن', 'عقاید'],
  'زبان': ['گرامر', 'واژگان', 'درک مطلب', 'نوشتار'],
  'تاریخ': ['تاریخ ایران', 'تاریخ جهان', 'تمدن‌ها'],
  'جغرافیا': ['جغرافیای طبیعی', 'جغرافیای انسانی', 'نقشه‌خوانی'],
  'فلسفه': ['منطق', 'فلسفه شرقی', 'فلسفه غربی'],
  'اقتصاد': ['اقتصاد خرد', 'اقتصاد کلان', 'مالیات'],
};

// ===== Mock Analytics Data =====
export const MOCK_DAILY_DATA = [
  { day: 'شنبه', hours: 5.5, tests: 35 },
  { day: 'یکشنبه', hours: 6, tests: 40 },
  { day: 'دوشنبه', hours: 4.5, tests: 25 },
  { day: 'سه‌شنبه', hours: 7, tests: 50 },
  { day: 'چهارشنبه', hours: 5, tests: 30 },
  { day: 'پنجشنبه', hours: 6.5, tests: 45 },
  { day: 'جمعه', hours: 3, tests: 15 },
];

export const MOCK_SUBJECT_DISTRIBUTION = [
  { name: 'ریاضی', value: 35, fill: '#5E6AD2' },
  { name: 'فیزیک', value: 25, fill: '#6E7AE0' },
  { name: 'شیمی', value: 20, fill: '#3EBA8C' },
  { name: 'زیست', value: 15, fill: '#9B8CF0' },
  { name: 'ادبیات', value: 5, fill: '#D89614' },
];

export const MOCK_ACTIVITY_DATA = [
  { name: 'شنبه', مطالعه: 120, مرور: 45, تست_آموزشی: 60, تست_سنجشی: 30 },
  { name: 'یکشنبه', مطالعه: 100, مرور: 60, تست_آموزشی: 45, تست_سنجشی: 40 },
  { name: 'دوشنبه', مطالعه: 90, مرور: 30, تست_آموزشی: 50, تست_سنجشی: 20 },
  { name: 'سه‌شنبه', مطالعه: 150, مرور: 50, تست_آموزشی: 70, تست_سنجشی: 45 },
  { name: 'چهارشنبه', مطالعه: 110, مرور: 40, تست_آموزشی: 55, تست_سنجشی: 35 },
  { name: 'پنجشنبه', مطالعه: 130, مرور: 55, تست_آموزشی: 65, تست_سنجشی: 40 },
  { name: 'جمعه', مطالعه: 60, مرور: 20, تست_آموزشی: 30, تست_سنجشی: 10 },
];

// ===== Mock Student Profiles (Advisor Dashboard) =====
export const MOCK_STUDENTS: StudentProfile[] = [
  {
    id: 's1',
    name: 'سارا محمدی',
    avatar: '🦊',
    grade: 'دوازدهم',
    major: 'تجربی',
    goal: 'کنکور',
    studyHoursPerWeek: 38,
    studyHoursTarget: 40,
    studyHoursTrend: 'up',
    mockExamScore: 78,
    previousMockScore: 72,
    konkurPercentile: 82,
    schoolGrades: { 'ریاضی': 18, 'فیزیک': 17, 'شیمی': 19, 'زیست': 18, 'ادبیات': 16, 'عربی': 15 },
    attendanceRate: 95,
    taskCompletionRate: 88,
    pomodoroSessionsPerWeek: 22,
    flashcardsMastered: 45,
    flashcardsTotal: 60,
    mood: 'good',
    motivationLevel: 8,
    stressLevel: 5,
    advisorNotes: 'پیشرفت مداوم. در زیست و شیمی قوی‌تر از بقیه دروس. در عربی نیاز به تقویت دارد.',
    lastSessionDate: '2025-01-18',
    weeksUntilExam: 14,
  },
  {
    id: 's2',
    name: 'امیرحسین رضایی',
    avatar: '🐺',
    grade: 'دوازدهم',
    major: 'ریاضی',
    goal: 'کنکور',
    studyHoursPerWeek: 22,
    studyHoursTarget: 40,
    studyHoursTrend: 'down',
    mockExamScore: 52,
    previousMockScore: 61,
    konkurPercentile: 38,
    schoolGrades: { 'ریاضی': 14, 'فیزیک': 11, 'شیمی': 13, 'ادبیات': 12, 'عربی': 10, 'زبان': 14 },
    attendanceRate: 72,
    taskCompletionRate: 45,
    pomodoroSessionsPerWeek: 5,
    flashcardsMastered: 8,
    flashcardsTotal: 40,
    mood: 'poor',
    motivationLevel: 3,
    stressLevel: 9,
    advisorNotes: 'افت شدید در دو هفته اخیر. احتمال فرسودگی تحصیلی. در فیزیک و عربی نمره بسیار پایین. کاهش چشمگیر ساعت مطالعه.',
    lastSessionDate: '2025-01-10',
    weeksUntilExam: 14,
  },
  {
    id: 's3',
    name: 'فاطمه احمدی',
    avatar: '🦁',
    grade: 'یازدهم',
    major: 'انسانی',
    goal: 'کنکور',
    studyHoursPerWeek: 30,
    studyHoursTarget: 35,
    studyHoursTrend: 'stable',
    mockExamScore: 65,
    previousMockScore: 63,
    konkurPercentile: 55,
    schoolGrades: { 'ادبیات': 17, 'عربی': 16, 'دینی': 18, 'تاریخ': 15, 'جغرافیا': 14, 'فلسفه': 13 },
    attendanceRate: 88,
    taskCompletionRate: 72,
    pomodoroSessionsPerWeek: 14,
    flashcardsMastered: 20,
    flashcardsTotal: 35,
    mood: 'fair',
    motivationLevel: 6,
    stressLevel: 6,
    advisorNotes: 'عملکرد متوسط و باثبات. در فلسفه و جغرافیا ضعیف‌تر. نیاز به تمرکز بیشتر بر دروس ضعیف.',
    lastSessionDate: '2025-01-15',
    weeksUntilExam: 66,
  },
  {
    id: 's4',
    name: 'محمد حسینی',
    avatar: '🐯',
    grade: 'فارغ‌التحصیل',
    major: 'تجربی',
    goal: 'کنکور',
    studyHoursPerWeek: 45,
    studyHoursTarget: 50,
    studyHoursTrend: 'up',
    mockExamScore: 85,
    previousMockScore: 80,
    konkurPercentile: 91,
    schoolGrades: { 'ریاضی': 19, 'فیزیک': 18, 'شیمی': 19, 'زیست': 20, 'ادبیات': 17, 'عربی': 16 },
    attendanceRate: 98,
    taskCompletionRate: 94,
    pomodoroSessionsPerWeek: 28,
    flashcardsMastered: 55,
    flashcardsTotal: 60,
    mood: 'excellent',
    motivationLevel: 9,
    stressLevel: 4,
    advisorNotes: 'عملکرد عالی و مداوم. فارغ‌التحصیل مصمم. فقط استرس کنکور را مدیریت کند. در ادبیات و عربی جا برای رشد دارد.',
    lastSessionDate: '2025-01-20',
    weeksUntilExam: 14,
  },
  {
    id: 's5',
    name: 'زهرا کریمی',
    avatar: '🦅',
    grade: 'دوازدهم',
    major: 'تجربی',
    goal: 'کنکور',
    studyHoursPerWeek: 18,
    studyHoursTarget: 35,
    studyHoursTrend: 'down',
    mockExamScore: 35,
    previousMockScore: 42,
    konkurPercentile: 15,
    schoolGrades: { 'ریاضی': 9, 'فیزیک': 8, 'شیمی': 10, 'زیست': 12, 'ادبیات': 11, 'عربی': 9 },
    attendanceRate: 55,
    taskCompletionRate: 25,
    pomodoroSessionsPerWeek: 2,
    flashcardsMastered: 3,
    flashcardsTotal: 30,
    mood: 'critical',
    motivationLevel: 2,
    stressLevel: 10,
    advisorNotes: 'وضعیت بحرانی. عدم حضور در کلاس‌ها، نمرات بسیار پایین، احتمال افسردگی. نیاز به جلسه فوری با مشاور تحصیلی و روانشناس.',
    lastSessionDate: '2025-01-05',
    weeksUntilExam: 14,
  },
  {
    id: 's6',
    name: 'علی نوری',
    avatar: '🐉',
    grade: 'دوازدهم',
    major: 'ریاضی',
    goal: 'هر دو',
    studyHoursPerWeek: 32,
    studyHoursTarget: 38,
    studyHoursTrend: 'stable',
    mockExamScore: 68,
    previousMockScore: 66,
    konkurPercentile: 60,
    schoolGrades: { 'ریاضی': 16, 'فیزیک': 15, 'شیمی': 14, 'ادبیات': 15, 'عربی': 13, 'زبان': 16 },
    attendanceRate: 82,
    taskCompletionRate: 68,
    pomodoroSessionsPerWeek: 12,
    flashcardsMastered: 15,
    flashcardsTotal: 40,
    mood: 'good',
    motivationLevel: 7,
    stressLevel: 6,
    advisorNotes: 'عملکرد متوسط رو به بالا. در ریاضی و زبان قوی‌تر. عربی و شیمی نقطه ضعف. هدف‌گذاری برای هر دو (کنکور و نهایی) فشار اضافه ایجاد کرده.',
    lastSessionDate: '2025-01-16',
    weeksUntilExam: 14,
  },
  {
    id: 's7',
    name: 'مینا صادقی',
    avatar: '🦢',
    grade: 'یازدهم',
    major: 'تجربی',
    goal: 'کنکور',
    studyHoursPerWeek: 35,
    studyHoursTarget: 35,
    studyHoursTrend: 'up',
    mockExamScore: 72,
    previousMockScore: 65,
    konkurPercentile: 70,
    schoolGrades: { 'ریاضی': 15, 'فیزیک': 14, 'شیمی': 16, 'زیست': 17, 'ادبیات': 18, 'عربی': 17 },
    attendanceRate: 92,
    taskCompletionRate: 82,
    pomodoroSessionsPerWeek: 18,
    flashcardsMastered: 30,
    flashcardsTotal: 45,
    mood: 'good',
    motivationLevel: 8,
    stressLevel: 4,
    advisorNotes: 'پیشرفت خوب در trimester اخیر. در زیست و ادبیات قوی. ریاضی و فیزیک نقطه ضعف. با برنامه‌ریزی مناسب می‌تواند به وضعیت عالی برسد.',
    lastSessionDate: '2025-01-19',
    weeksUntilExam: 66,
  },
  {
    id: 's8',
    name: 'رضا طاهری',
    avatar: '🐻',
    grade: 'دوازدهم',
    major: 'تجربی',
    goal: 'کنکور',
    studyHoursPerWeek: 28,
    studyHoursTarget: 40,
    studyHoursTrend: 'stable',
    mockExamScore: 58,
    previousMockScore: 57,
    konkurPercentile: 42,
    schoolGrades: { 'ریاضی': 12, 'فیزیک': 13, 'شیمی': 12, 'زیست': 14, 'ادبیات': 14, 'عربی': 11 },
    attendanceRate: 78,
    taskCompletionRate: 55,
    pomodoroSessionsPerWeek: 8,
    flashcardsMastered: 10,
    flashcardsTotal: 35,
    mood: 'fair',
    motivationLevel: 5,
    stressLevel: 7,
    advisorNotes: 'عملکرد متوسط و راکد. بدون پیشرفت قابل توجه. بیشترین مشکل در عربی و ریاضی. ساعات مطالعه کمتر از حد لازم. نیاز به بازنگری اساسی برنامه.',
    lastSessionDate: '2025-01-12',
    weeksUntilExam: 14,
  },
];

// ===== Mock Institute Advisors =====
export const MOCK_INSTITUTE_ADVISORS: InstituteAdvisor[] = [
  {
    id: 'adv1',
    name: 'دکتر محمدی',
    phone: '09121234567',
    avatar: '👨‍🏫',
    specialty: 'ریاضی و فیزیک',
    studentCount: 3,
    isActive: true,
    joinDate: '2024-09-01',
  },
  {
    id: 'adv2',
    name: 'سرکار خانم احمدی',
    phone: '09129876543',
    avatar: '👩‍🏫',
    specialty: 'تجربی (زیست و شیمی)',
    studentCount: 2,
    isActive: true,
    joinDate: '2024-09-15',
  },
  {
    id: 'adv3',
    name: 'آقای رضایی',
    phone: '09123456789',
    avatar: '🧑‍🏫',
    specialty: 'انسانی',
    studentCount: 1,
    isActive: true,
    joinDate: '2024-10-01',
  },
  {
    id: 'adv4',
    name: 'سرکار خانم موسوی',
    phone: '09124567890',
    avatar: '👩‍💻',
    specialty: 'زبان و ادبیات',
    studentCount: 2,
    isActive: false,
    joinDate: '2024-08-20',
  },
];

// ===== Mock Institute Students =====
export const MOCK_INSTITUTE_STUDENTS: InstituteStudent[] = [
  {
    id: 'ist1',
    name: 'سارا محمدی',
    phone: '09131111111',
    avatar: '🦊',
    grade: 'دوازدهم',
    major: 'تجربی',
    assignedAdvisorId: 'adv2',
    weeklyCompletionRate: 88,
    totalStudyHours: 38,
    mockExamScore: 78,
    status: 'excellent',
    joinDate: '2024-09-01',
  },
  {
    id: 'ist2',
    name: 'امیرحسین رضایی',
    phone: '09132222222',
    avatar: '🐺',
    grade: 'دوازدهم',
    major: 'ریاضی',
    assignedAdvisorId: 'adv1',
    weeklyCompletionRate: 45,
    totalStudyHours: 22,
    mockExamScore: 52,
    status: 'at-risk',
    joinDate: '2024-09-01',
  },
  {
    id: 'ist3',
    name: 'فاطمه احمدی',
    phone: '09133333333',
    avatar: '🦁',
    grade: 'یازدهم',
    major: 'انسانی',
    assignedAdvisorId: 'adv3',
    weeklyCompletionRate: 72,
    totalStudyHours: 30,
    mockExamScore: 65,
    status: 'good',
    joinDate: '2024-09-15',
  },
  {
    id: 'ist4',
    name: 'محمد حسینی',
    phone: '09134444444',
    avatar: '🐯',
    grade: 'فارغ‌التحصیل',
    major: 'تجربی',
    assignedAdvisorId: 'adv1',
    weeklyCompletionRate: 94,
    totalStudyHours: 45,
    mockExamScore: 85,
    status: 'excellent',
    joinDate: '2024-09-01',
  },
  {
    id: 'ist5',
    name: 'زهرا کریمی',
    phone: '09135555555',
    avatar: '🦅',
    grade: 'دوازدهم',
    major: 'تجربی',
    assignedAdvisorId: null,
    weeklyCompletionRate: 25,
    totalStudyHours: 18,
    mockExamScore: 35,
    status: 'critical',
    joinDate: '2024-10-01',
  },
  {
    id: 'ist6',
    name: 'علی نوری',
    phone: '09136666666',
    avatar: '🐉',
    grade: 'دوازدهم',
    major: 'ریاضی',
    assignedAdvisorId: 'adv1',
    weeklyCompletionRate: 68,
    totalStudyHours: 32,
    mockExamScore: 68,
    status: 'good',
    joinDate: '2024-09-15',
  },
  {
    id: 'ist7',
    name: 'مینا صادقی',
    phone: '09137777777',
    avatar: '🦢',
    grade: 'یازدهم',
    major: 'تجربی',
    assignedAdvisorId: 'adv2',
    weeklyCompletionRate: 82,
    totalStudyHours: 35,
    mockExamScore: 72,
    status: 'good',
    joinDate: '2024-09-15',
  },
  {
    id: 'ist8',
    name: 'رضا طاهری',
    phone: '09138888888',
    avatar: '🐻',
    grade: 'دوازدهم',
    major: 'تجربی',
    assignedAdvisorId: null,
    weeklyCompletionRate: 55,
    totalStudyHours: 28,
    mockExamScore: 58,
    status: 'fair',
    joinDate: '2024-10-01',
  },
  {
    id: 'ist9',
    name: 'نرگس عباسی',
    phone: '09139999999',
    avatar: '🦋',
    grade: 'دهم',
    major: 'ریاضی',
    assignedAdvisorId: 'adv4',
    weeklyCompletionRate: 91,
    totalStudyHours: 20,
    mockExamScore: 70,
    status: 'excellent',
    joinDate: '2024-11-01',
  },
  {
    id: 'ist10',
    name: 'حسین قاسمی',
    phone: '09130000000',
    avatar: '🦉',
    grade: 'یازدهم',
    major: 'تجربی',
    assignedAdvisorId: 'adv4',
    weeklyCompletionRate: 40,
    totalStudyHours: 15,
    mockExamScore: 42,
    status: 'at-risk',
    joinDate: '2024-11-15',
  },
];

/* Legacy super-admin mock data removed. */
/*
export const MOCK_PLATFORM_INSTITUTES: PlatformInstitute[] = [
  {
    id: 'inst1',
    name: 'آموزشگاه هدف',
    logoUrl: null,
    managerName: 'آقای احمدی',
    managerPhone: '09121111111',
    subscriptionPlan: 'pro',
    status: 'active',
    studentCount: 10,
    advisorCount: 4,
    createdAt: '2024-09-01',
    avgCompletionRate: 66,
  },
  {
    id: 'inst2',
    name: 'موسسه نور دانش',
    logoUrl: null,
    managerName: 'سرکار خانم رضایی',
    managerPhone: '09129876543',
    subscriptionPlan: 'enterprise',
    status: 'active',
    studentCount: 25,
    advisorCount: 8,
    createdAt: '2024-06-15',
    avgCompletionRate: 78,
  },
  {
    id: 'inst3',
    name: 'آکادمی پارسیان',
    logoUrl: null,
    managerName: 'دکتر محمدی',
    managerPhone: '09123456789',
    subscriptionPlan: 'basic',
    status: 'active',
    studentCount: 15,
    advisorCount: 5,
    createdAt: '2024-08-01',
    avgCompletionRate: 61,
  },
  {
    id: 'inst4',
    name: 'آموزشگاه آینده',
    logoUrl: null,
    managerName: 'آقای کریمی',
    managerPhone: '09124567890',
    subscriptionPlan: 'free',
    status: 'trial',
    studentCount: 5,
    advisorCount: 2,
    createdAt: '2025-01-10',
    avgCompletionRate: 45,
  },
  {
    id: 'inst5',
    name: 'موسسه هوشمند',
    logoUrl: null,
    managerName: 'سرکار خانم موسوی',
    managerPhone: '09125678901',
    subscriptionPlan: 'pro',
    status: 'suspended',
    studentCount: 12,
    advisorCount: 3,
    createdAt: '2024-07-20',
    avgCompletionRate: 52,
  },
];

// ===== Mock Global Users (Super Admin) =====
export const MOCK_GLOBAL_USERS: GlobalUser[] = [
  {
    id: 'gu1',
    name: 'سارا محمدی',
    avatar: '🦊',
    phone: '09131111111',
    role: 'student',
    instituteId: 'inst1',
    instituteName: 'آموزشگاه هدف',
    status: 'active',
    completionRate: 88,
    studyHours: 38,
    mockExamScore: 78,
    joinDate: '2024-09-01',
    lastActiveDate: '2025-01-20',
  },
  {
    id: 'gu2',
    name: 'امیرحسین رضایی',
    avatar: '🐺',
    phone: '09132222222',
    role: 'student',
    instituteId: 'inst1',
    instituteName: 'آموزشگاه هدف',
    status: 'active',
    completionRate: 45,
    studyHours: 22,
    mockExamScore: 52,
    joinDate: '2024-09-01',
    lastActiveDate: '2025-01-18',
  },
  {
    id: 'gu3',
    name: 'دکتر محمدی',
    avatar: '👨‍🏫',
    phone: '09121234567',
    role: 'advisor',
    instituteId: 'inst1',
    instituteName: 'آموزشگاه هدف',
    status: 'active',
    completionRate: 85,
    studyHours: 0,
    mockExamScore: 0,
    joinDate: '2024-09-01',
    lastActiveDate: '2025-01-20',
  },
  {
    id: 'gu4',
    name: 'سرکار خانم احمدی',
    avatar: '👩‍🏫',
    phone: '09129876543',
    role: 'advisor',
    instituteId: 'inst1',
    instituteName: 'آموزشگاه هدف',
    status: 'active',
    completionRate: 90,
    studyHours: 0,
    mockExamScore: 0,
    joinDate: '2024-09-15',
    lastActiveDate: '2025-01-19',
  },
  {
    id: 'gu5',
    name: 'فاطمه احمدی',
    avatar: '🦁',
    phone: '09133333333',
    role: 'student',
    instituteId: 'inst1',
    instituteName: 'آموزشگاه هدف',
    status: 'active',
    completionRate: 72,
    studyHours: 30,
    mockExamScore: 65,
    joinDate: '2024-09-15',
    lastActiveDate: '2025-01-17',
  },
  {
    id: 'gu6',
    name: 'محمد حسینی',
    avatar: '🐯',
    phone: '09134444444',
    role: 'student',
    instituteId: 'inst1',
    instituteName: 'آموزشگاه هدف',
    status: 'active',
    completionRate: 94,
    studyHours: 45,
    mockExamScore: 85,
    joinDate: '2024-09-01',
    lastActiveDate: '2025-01-20',
  },
  {
    id: 'gu7',
    name: 'زهرا کریمی',
    avatar: '🦅',
    phone: '09135555555',
    role: 'student',
    instituteId: 'inst1',
    instituteName: 'آموزشگاه هدف',
    status: 'suspended',
    completionRate: 25,
    studyHours: 18,
    mockExamScore: 35,
    joinDate: '2024-10-01',
    lastActiveDate: '2025-01-05',
  },
  {
    id: 'gu8',
    name: 'نرگس عباسی',
    avatar: '🦋',
    phone: '09139999999',
    role: 'student',
    instituteId: 'inst2',
    instituteName: 'موسسه نور دانش',
    status: 'active',
    completionRate: 91,
    studyHours: 40,
    mockExamScore: 82,
    joinDate: '2024-06-20',
    lastActiveDate: '2025-01-20',
  },
  {
    id: 'gu9',
    name: 'حسین قاسمی',
    avatar: '🦉',
    phone: '09130000000',
    role: 'student',
    instituteId: 'inst2',
    instituteName: 'موسسه نور دانش',
    status: 'active',
    completionRate: 67,
    studyHours: 28,
    mockExamScore: 60,
    joinDate: '2024-07-01',
    lastActiveDate: '2025-01-19',
  },
  {
    id: 'gu10',
    name: 'سرکار خانم رضایی',
    avatar: '👩‍💼',
    phone: '09129876543',
    role: 'institute_manager',
    instituteId: 'inst2',
    instituteName: 'موسسه نور دانش',
    status: 'active',
    completionRate: 0,
    studyHours: 0,
    mockExamScore: 0,
    joinDate: '2024-06-15',
    lastActiveDate: '2025-01-20',
  },
  {
    id: 'gu11',
    name: 'دکتر سلطانی',
    avatar: '👨‍⚕️',
    phone: '09126666666',
    role: 'advisor',
    instituteId: 'inst2',
    instituteName: 'موسسه نور دانش',
    status: 'active',
    completionRate: 92,
    studyHours: 0,
    mockExamScore: 0,
    joinDate: '2024-06-20',
    lastActiveDate: '2025-01-20',
  },
  {
    id: 'gu12',
    name: 'آقای کریمی',
    avatar: '👨‍💼',
    phone: '09124567890',
    role: 'institute_manager',
    instituteId: 'inst4',
    instituteName: 'آموزشگاه آینده',
    status: 'active',
    completionRate: 0,
    studyHours: 0,
    mockExamScore: 0,
    joinDate: '2025-01-10',
    lastActiveDate: '2025-01-19',
  },
  {
    id: 'gu13',
    name: 'علی نوری',
    avatar: '🐉',
    phone: '09136666666',
    role: 'student',
    instituteId: 'inst3',
    instituteName: 'آکادمی پارسیان',
    status: 'active',
    completionRate: 68,
    studyHours: 32,
    mockExamScore: 68,
    joinDate: '2024-08-15',
    lastActiveDate: '2025-01-18',
  },
  {
    id: 'gu14',
    name: 'مینا صادقی',
    avatar: '🦢',
    phone: '09137777777',
    role: 'student',
    instituteId: 'inst3',
    instituteName: 'آکادمی پارسیان',
    status: 'active',
    completionRate: 82,
    studyHours: 35,
    mockExamScore: 72,
    joinDate: '2024-08-20',
    lastActiveDate: '2025-01-19',
  },
  {
    id: 'gu15',
    name: 'سرکار خانم موسوی',
    avatar: '👩‍💻',
    phone: '09125678901',
    role: 'institute_manager',
    instituteId: 'inst5',
    instituteName: 'موسسه هوشمند',
    status: 'suspended',
    completionRate: 0,
    studyHours: 0,
    mockExamScore: 0,
    joinDate: '2024-07-20',
    lastActiveDate: '2024-12-15',
  },
  {
    id: 'gu16',
    name: 'آقای رضایی',
    avatar: '🧑‍🏫',
    phone: '09123456789',
    role: 'advisor',
    instituteId: 'inst1',
    instituteName: 'آموزشگاه هدف',
    status: 'active',
    completionRate: 80,
    studyHours: 0,
    mockExamScore: 0,
    joinDate: '2024-10-01',
    lastActiveDate: '2025-01-18',
  },
  {
    id: 'gu17',
    name: 'سرکار خانم موسوی',
    avatar: '👩‍💻',
    phone: '09124567890',
    role: 'advisor',
    instituteId: 'inst1',
    instituteName: 'آموزشگاه هدف',
    status: 'active',
    completionRate: 75,
    studyHours: 0,
    mockExamScore: 0,
    joinDate: '2024-08-20',
    lastActiveDate: '2025-01-15',
  },
];

// ===== Mock Platform Engagement Data (Super Admin Charts) =====
export const MOCK_PLATFORM_ENGAGEMENT = [
  { month: 'مهر', students: 45, advisors: 12, completionRate: 62 },
  { month: 'آبان', students: 58, advisors: 15, completionRate: 65 },
  { month: 'آذر', students: 67, advisors: 18, completionRate: 68 },
  { month: 'دی', students: 72, advisors: 20, completionRate: 70 },
  { month: 'بهمن', students: 78, advisors: 22, completionRate: 72 },
  { month: 'اسفند', students: 82, advisors: 24, completionRate: 75 },
];
*/

// ===== Mock Exams =====
export const MOCK_EXAMS: Exam[] = [
  {
    id: 'exam1',
    title: 'آزمون جامع ریاضی - اسفند',
    subject: 'ریاضی',
    subjectColor: '#5E6AD2',
    date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    startTime: '08:00',
    duration: 120,
    totalScore: 100,
    studentIds: ['s1', 's2', 's4', 's6'],
    status: 'upcoming',
    results: [],
    createdBy: 'adv1',
    createdAt: '2025-01-15',
  },
  {
    id: 'exam2',
    title: 'آزمون تستی فیزیک - بهمن',
    subject: 'فیزیک',
    subjectColor: '#D89614',
    date: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    startTime: '14:00',
    duration: 90,
    totalScore: 100,
    studentIds: ['s1', 's2', 's6'],
    status: 'upcoming',
    results: [],
    createdBy: 'adv1',
    createdAt: '2025-01-10',
  },
  {
    id: 'exam3',
    title: 'آزمون شیمی - دی',
    subject: 'شیمی',
    subjectColor: '#E5484D',
    date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    startTime: '10:00',
    duration: 90,
    totalScore: 100,
    studentIds: ['s1', 's4', 's5'],
    status: 'completed',
    results: [
      { studentId: 's1', score: 82, rank: 1 },
      { studentId: 's4', score: 91, rank: null },
      { studentId: 's5', score: 38, rank: 3 },
    ],
    createdBy: 'adv2',
    createdAt: '2025-01-05',
  },
  {
    id: 'exam4',
    title: 'آزمون زیست‌شناسی - دی',
    subject: 'زیست',
    subjectColor: '#9B8CF0',
    date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
    startTime: '08:00',
    duration: 120,
    totalScore: 100,
    studentIds: ['s1', 's4', 's7'],
    status: 'completed',
    results: [
      { studentId: 's1', score: 75, rank: 2 },
      { studentId: 's4', score: 95, rank: 1 },
      { studentId: 's7', score: 68, rank: 3 },
    ],
    createdBy: 'adv2',
    createdAt: '2024-12-28',
  },
];
